export default function loadCharacters(name = 'all') {
  const characters = [
    {
      name: 'Holly Flax',
      image: '/team/holly.jpg',
      seasons: [4, 5, 7],
      occupation: 'Human Resources',
      aliases: ['Fanny Smellmore', 'DJ Jazzy Flax', 'Princess Nincompoop', 'Necropolis'],
      brand: 'Nashua',
      portrayed: 'Amy Ryan',
      firstEp: 'Goodbye, Toby',
      quotes: ['Everything he does is sexy. He has this undeniable animal magnetism, he\'s a jungle cat. The man exudes Sex!', 'Your wife becoming...be will I.'],
      trivia:
        'Holly was introduced to be the first person who actually liked Michael, allowing his character to mature. She was not intended to be his life partner, and was planned to be in only six episodes.',
    },
    {
      name: 'Michael Scott',
      image: '/team/michael.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7],
      occupation: 'Regional Manager',
      aliases: [
        'Ping',
        'Michael the Magic',
        'Michael Scarn',
        'Michael Klump',
        'Date Mike',
        'Mike (by Darryl)',
        'Blind Guy McSqueezy',
        'Prison Mike',
        'Caleb Crawdad',
        'Master of Guidance',
        'Michael Wonka',
        'Reginald Poofta',
        'Michael Scotch',
        'Spiros',
        'Orville Tootenbacher',
        'Jesus Christ',
        'Johnny Carson',
        'Michael J Fox',
        'Mr. Fox',
        'Nicki Minaj',
        'The Incredible Mr. Fox',
        'Santa Bond',
        'Beyoncé',
        "Captain Bruisin'",
        'Michael Jackson',
        "Ryan's Girlfriend",
        'Dennis the Menace',
        'Eddie Murphy',
        'Spicoli Guy',
        'MC Mike Scott',
        'Michael Snot',
        'Elton',
        'Mr. Scott (By The High School Kids)',
      ],
      brand: 'Scranton',
      portrayed: 'Steve Carell',
      firstEp: 'Pilot',
      quotes: [
        'If I had a gun with two bullets and I was in a room with Hitler, Bin Laden, and Toby, I would shoot Toby twice.',
        'Marrying me will you be?',
        'Occasionally, I’ll hit somebody with my car. So sue me.',
        'Everybody stay calm! Stay f*&#!#% calm!',
        'And I knew exactly what to do. But in a much more real sense, I had no idea what to do.',
        'I feel like all my kids grew up, and then they married each other. It’s every parent’s dream.',
        'Dwight, you ignorant slut!',
        'Well, Happy Birthday Jesus. Sorry your party’s so lame.',
        'Sometimes I’ll start a sentence, and I don’t even know where it’s going. I just hope I find it along the way.',
        "There are certain things a boss does not share with his employees. His salary, that would depress them. His bed, it--- And I am not going to tell them that I'll be reading their e-mails.",
        "Am I going to tell them? No, I am not going to tell them. I don't see the point of that. As a doctor, you would not tell a patient if they had cancer.",
        'Wikipedia Is The Best Thing Ever. Anyone In The World Can Write Anything They Want About Any Subject, So You Know You Are Getting The Best Possible Information.',
        'Hate To See You Leave But Love To Watch You Go. ‘Cause Of Your Butt.',
        'I Love Inside Jokes. Love To Be A Part Of One Someday.',
        'It’s Never Too Early For Ice-Cream, Jim.',
        'I. Declare. Bankruptcy!',
        'That’s What She Said!',
        'Yes, it is true. I, Michael Scott, am signing up with an online dating service. Thousands of people have done it, and I am going to do it. I need a username. And... I have a great one [types]. Little kid lover. That way, people will know exactly where my priorities are at.',
        "I'll catch you on the flippity-flip. Bye!",
        "It's not that children make me uncomfortable, it's just that, why be a dad when you can be a fun uncle? I've never heard of anyone rebelling against their fun uncle.",
        "Close your eyes. Picture a convict. What's he wearing? Nothing special, baseball cap on backwards, baggy pants... he says something ordinary like... 'yo, thats shizzle.' Okay. Now slowly open your eyes again. Who are you picturing? A black man? Wrong. That was a white woman. Surprised? Well, shame on you.",
        "You may look around and see two groups here: white collar, blue collar. But I don't see it that way, and you know why not? Because I am collar-blind.",
        'Fool me once, strike one. Fool me twice, strike three.',
        "Sometimes you have to take a break from being the kind of boss that's always trying to teach people things. Sometimes you just have to be the boss of dancing.",
        'Make friends first, make sales second, make love third. In no particular order.',
        'People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake. And to me the choice is easy.',
      ],
      trivia:
        'His role models are Bob Hope, Abraham Lincoln, Bono, and God. Michael lost his virginity when he was 28. His signature saying is "That\'s what she said". Michael is almost incapable of keeping a secret. His deepest fear is being alone.',
    },
    {
      name: 'Andy Bernard',
      aliases: [
        'Nard Dog',
        'Nard Pup',
        'Bro Nard',
        'Nard Man',
        'Boner Champ',
        'Ace',
        'Drew',
        'Moon Face',
        'Office Pariah',
        'Buzz',
        'Hubble',
        'Puke',
        'Pencil Dick',
        'Lionel Frankenstein',
        'Jelly Roll',
        'Baby Wawa',
        'King Butt',
        'Iceman',
        'Funny Guy',
        'Jabroni',
        'Bernard Dog',
        'Sly Dog',
        'Older Male Lab Assistant Number One',
        'Demandy',
        'Regional Manager',
        'Singing Buffoon',
      ],
      occupation: 'Director of Sales',
      brand: 'Stamford',
      image: '/team/andy.jpg',
      seasons: [3, 4, 5, 6, 7, 8, 9],
      portrayed: 'Ed Helms',
      firstEp: 'Gay Witch Hunt',
      quotes: [
        'I wish there was a way to know you’re in the good old days, before you’ve actually left them.',
        "You can't let a girl feel good about herself. It will backfire on you. Every compliment has to be backhanded. 'Oh I like your dress, but I'd like it more if you had prettier hair.'",
        "I'll be the Number Two guy here in Scranton in six weeks. How? Name repetition, personality mirroring, and never breaking off a handshake. I'm always thinking one step ahead. Like a carpenter that makes stairs.",
        'Sorry I annoyed you with my friendship.',
        'Andy Bernard Does Not Lose Contests. He Wins Them… Or He Quits Them Because They Are Unfair.',
      ],
      trivia:
        'Andy\'s trademark "Rid-dit-dit-di-doo" was something that some of Ed Helms\'s middle school classmates used. It was an expression of triumph after getting off a good zinger.',
    },
    {
      name: 'Erin Hannon',
      image: '/team/erin.jpg',
      seasons: [5, 6, 7, 8, 9],
      occupation: 'Receptionist',
      aliases: [
        'Kelly Erin Hannon (Full name)',
        'Hannon (by Charles)',
        'E (by Darryl)',
        'Princess Ding Dong (by Meredith)',
        'Tabitha',
        'Space Orphan',
      ],
      brand: 'Scranton',
      portrayed: 'Ellie Kemper',
      firstEp: 'Michael Scott Paper Company',
      quotes: [
        "Disposable cameras are fun, but it seems a little wasteful. You never get to see your pictures. If it's an important event that you want to remember, I recommend using a real camera.",
      ],
      trivia:
        'Kemper described herself as a "huge fan" of the show and was thrilled to be cast. She was originally intended to do only one episode, then was kept for the final two episodes of the fifth season, before becoming a series regular.',
    },
    {
      name: 'Kevin Malone',
      image: '/team/kevin.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Accountant',
      aliases: [
        'Kev',
        'Chumbo',
        'Kool-Aid Man',
        'Papa Bear',
        'Child Molester',
        'Dumpster man',
        'Ashton Kutcher',
        'Cookie Monster',
      ],
      brand: 'Scranton',
      portrayed: 'Brian Baumgartner',
      firstEp: 'Pilot',
      quotes: [
        'When me president, they see. They see.',
        'I am immensely proud of what I did for that turtle!',
        'Yes, me do.',
        'Body strong. Sleep big last night.',
        'Why waste time say lot word when few word do trick?',
      ],
      trivia:
        'During the time period between the second and third seasons, NBC posted The Accountants, a season of "webisodes" with Kevin, Oscar, and Angela attempting to solve an accounting error. The error ends up being the fault of Angela and when it is discovered, Kevin says it is the best day of his life.',
    },
    {
      name: 'Jan Levinson',
      image: '/team/jan.jpg',
      seasons: [1, 2, 3, 4, 5],
      occupation: 'Vice President of Sales',
      aliases: [
        'Jan Levinson-Gould',
        'Jan',
        'Hillary Rodham Clinton',
        'Godzillary',
        'Lan Jevinson',
        'Ice Queen',
        'Dirty Bitch',
        'Urkel Grue',
        'Babe',
      ],
      brand: 'Dunder Mifflin',
      portrayed: 'Melora Hardin',
      firstEp: 'Pilot',
      quotes: [],
      trivia:
        'In the pilot, the character of Jan was a single-episode guest, with the possibility of becoming a recurring character. During filming of that episode, Melora Hardin, Steve Carell and Greg Daniels laughed at the weird dynamic between Jan and Michael and if the show made it to a second season, "we should have them hook up".',
    },
    {
      name: 'Darryl Philbin',
      image: '/team/darryl.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Warehouse Assistant',
      aliases: ['Regis', 'Reg', 'Rog', 'Darryl Rogers', 'Mitta Rogers', 'Darnell'],
      brand: 'Scranton',
      portrayed: 'Craig Robinson',
      firstEp: 'The Alliance',
      quotes: [
        "In a gang world, we use something called fluffy fingers. That's when someone really gets in your face, you know you just, start ticklin' 'em. And he starts tickling you. And pretty soon you laughing and hugging. Before you know it, you've forgotten the whole thing. Y'all just go to church together, and get an ice cream cone.",
      ],
      trivia:
        'As a subtle prank and possible retort to Michael\'s antics, Darryl teaches Michael "black man phrases", such as "fleece it out", "goin\' mach five", "bippity boppity, gimme the zoppity", and "dinkin\' flicka." In addition, Darryl teaches Michael a handshake that Michael believes to be "ghetto".',
    },
    {
      name: 'Oscar Martinez',
      image: '/team/oscar.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Special Projects Manager',
      aliases: [
        'C-Span',
        'Oscar Mayer Weiner Lover',
        'Bacchus God of Wine',
        'Actually',
        'Faggy (Michael)',
        'Oscar the Homosexual Accountant (Michael)',
        'Gay',
        'Big-O (by Luke Cooper)',
      ],
      brand: 'Scranton',
      portrayed: 'Oscar Nunez',
      firstEp: 'Pilot',
      quotes: [
        "I didn't realize how many of Angela's opinions I agreed with...until she tried to have my knee caps shattered for sleeping with her husband.",
        'Saddle Shoes With Denim? I Will Literally Call Protective Services.',
      ],
      trivia:
        'Oscar inserts himself into a lot of conversations to add facts or correct grammar, he tends to use "actually" a lot when doing so. In a deleted scene from "Gay Witch Hunt", Oscar points out that he mentioned that he was gay during his job interview, but Michael thought it was a joke.',
    },
    {
      name: 'Pam Beesly',
      image: '/team/pam.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Receptionist',
      aliases: [
        'Beesly',
        'Office Mattress',
        'Pamcake',
        'PamPam and her Pam Pams',
        'Bart Simpson of Scranton',
        'Pam-Pam!',
        'Pama-lama-ding-dong',
        'Big Pregs',
        "Pam, Pam, thank you ma'am",
        'Pam-burger-with-cheese',
        'Pamera',
        'Pam-M-S',
        'Pan',
        'Spamster',
        "Pam, Ms. Beesly if you're nasty",
        'Ampay',
        'Christmas Pam',
        'Candied Pams',
        'Pam-Chop',
        'Pamcasso',
        'Pam-ola',
        'Pretty Pam',
        'Pammy',
        'Little Miss Thing',
        'New York',
      ],
      brand: 'Scranton',
      portrayed: 'Jenna Fischer',
      firstEp: 'Pilot',
      quotes: [
        'Once every hour, someone is involved in an internet scam. That man is Michael Scott.',
        "It's performance review day, company-wide. Last year, my performance review started with Michael asking me what my hopes and dreams were, and it ended with him telling me he could bench-press 190 pounds. So, I don't really know what to expect.",
        'I feel God in this Chili’s tonight.',
        'There’s a lot of beauty in ordinary things. Isn’t that kind of the point?',
      ],
      trivia:
        "Pam wears a pink cardigan in episodes where it is suggested that she recently had sex. See Pam's lucky pink cardigan. Jenna Fischer and Angela Kinsey are good friends in real life. Pam and Dwight form a brief friendship while Dwight is suffering from a concussion.",
    },
    {
      name: 'Jim Halpert',
      image: '/team/jim.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Sales Representative',
      aliases: [
        'Fat Halpert',
        'Tuna',
        'Big Tuna (by Andy)',
        'Big Haircut (by Andy)',
        'Halpert',
        'The Hot One',
        'Jimothy',
        'Big Haircut',
        'Thin Sliced Tuna',
        'James Trickington',
        'Jim Bag',
        'William Buttlicker',
        'Mr Balance (by Dwight)',
        'Skippy',
        'Zuckerberg',
        'Jimmy',
        'Tall Guy (by Creed)',
        'Tuna Turner',
        'The Original Fry Cook',
        'Jimbo',
        'Jim Samtanko',
      ],
      brand: 'Scranton',
      portrayed: 'John Krasinski',
      firstEp: 'Pilot',
      quotes: [
        "It's true. I'm having a party. I've got three cases of imported beer, a karaoke machine, and I didn't invite Michael. So three ingredients for a great party. And it's nothing personal, I just think that if he were there, people wouldn't be able to relax, and you know, have fun, and my roommate wants to meet everybody. Because I'm pretty sure he thinks that I'm making Dwight up. [sighs] He is very real.",
        "I had feelings today for a coworker that I haven't had in years... In my defense he was grabbing my crotch fairly aggressively at the time.",
        'Bears. Beets. Battlestar Galactica.',
        "Right now, this is just a job. If I advance any higher in this company, then this would be my career. And, well, if this were my career? I'd have to throw myself in front of a train.",
      ],
      trivia:
        'Jim has appeared in every single episode of The Office with the exception of "Mafia," in which only his voice can be heard.',
    },
    {
      name: 'Dwight Schrute',
      image: '/team/dwight.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Assistant to the Regional Manager',
      aliases: [
        'D',
        'D-Money',
        'Dwayne',
        'Possum',
        'Mr. Poop',
        'Mr. Snoot',
        'Dwight Fart Schrute',
        'Jackhammer',
        'Gun Safety Dwight',
        'Big City',
        'Recyclops',
        'Michael Scotch',
        'Samuel L. Chang',
        'Bobble Head Joe',
        'Dwight Danger Schrute',
        'Dunder Mifflin Head salesman',
        'Assistant to the Regional Manager',
        'D.K.S.',
        'Monkey Trainer',
        'D-Dub-Dog',
        'Schru-berry Blue',
        'Dwigt',
        'D.K Schrute',
        'Dragon',
        'Computron',
        'That other jackass',
        'Dwight Shelford',
        'Jacques Souvenier',
      ],
      brand: 'Scranton',
      portrayed: 'Rainn Wilson',
      firstEp: 'Pilot',
      quotes: [
        "Jim is gone. He's gone. I miss him so much. Ooooh I cry myself to sleep, Jim! False. I do not miss him.",
        'Would I ever leave this company? Look, I’m all about loyalty. In fact, I feel like part of what I’m being paid for here is my loyalty. But if there were somewhere else that valued loyalty more highly… I’m going wherever they value loyalty the most.',
        'I am fast. To give you a reference point I am somewhere between a snake and a mongoose… And a panther.',
        'Security in this office park is a joke. Last year I came to work with my spud-gun in a duffel bag. I sat at my desk all day with a rifle that shoots potatoes at 60 pounds per square inch. Can you imagine if I was deranged?',
        'I grew up on a farm. I have seen animals having sex in every position imaginable. Goat on chicken. Chicken on goat. Couple of chickens doing a goat, couple of pigs watching.',
        'Through concentration, I can raise and lower my cholesterol at will.',
        "Whenever I'm about to do something, I think, 'Would an idiot do that?' And if they would, I do not do that thing.",
        'It has to be official, and it has to be urine.',
        "I have been Michael's #2 guy for about 5 years. And we make a great team. We're like one of those classic famous teams. He's like Mozart, and I'm like Mozart's friend. No. I'm like Butch Cassidy, and Michael is like Mozart. You try and hurt Mozart; you're going to get a bullet in your head courtesy of Butch Cassidy.",
        'I.D. badges are long overdue. Security in this office park is a joke. Last year, I came to work with my spud gun in a duffel bag. I sat at my desk all day, with a rifle that shoots potatoes at 60 pounds per square inch. Can you imagine if I was deranged?',
        'Why Are All These People Here? There Are Too Many People On This Earth. We Need A New Plague.',
        'You Couldn’t Handle My Undivided Attention.',
        'How Would I Describe Myself? Three Words. Hard-working. Alpha Male. Jackhammer. Merciless. Insatiable.',
        'Welcome to the Hotel Hell. Check-in time in now, check-out time is never.',
        "I'm the owner.. the co-owner. With Satan!",
        'The Japanese camp guards of World War II always chose one man to kill whenever a batch of new prisoners arrived. I always wondered how they chose the man who was to die. I think I would have been good at choosing the person.',
      ],
      trivia:
        'In the episode "Valentine\'s Day", Dwight is given a bobblehead doll as a Valentine\'s gift, from Angela. Following the episode, fans of the show petitioned NBC to make the bobblehead doll available for purchase on their online store. NBC responded by creating an initial run of 4,000 bobblehead dolls, which sold out almost immediately.',
    },
    {
      name: 'Angela Martin',
      aliases: [
        'Monkey',
        'Kitchen Witch',
        'Voodoo Mama Juju',
        'Juju Boo-Boo',
        'Pumpkin',
        'Andrea, The Office Bitch',
        'Booster Seat',
        'Angelo',
        'Little Onion',
      ],
      occupation: 'Senior Accountant',
      brand: 'Scranton',
      image: '/team/angela.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      portrayed: 'Angela Kinsey',
      firstEp: 'Pilot',
      quotes: [
        'If you pray enough, you can change yourself into a cat person.',
        'I know that patience and loyalty are good, and virtuous traits. But sometimes I just think you need to grow a pair.',
        "I'm not gaining anything from this seminar. I'm a professional woman. The head of accounting. I'm in the healthiest relationship of my life. I just think it's insulting that Jan thinks we need this. And, apparently, judging from her outfit, Jan aspires to be a whore.",
        'Poop is raining from the ceilings. Poop!',
      ],
      trivia:
        'Kinsey was pregnant during the filming of season 4, noticeably so from the episodes Dinner Party through Goodbye, Toby. The producers decided not to incorporate her pregnancy into the story line and shot around it.',
    },
    {
      name: 'Kelly Kapoor',
      image: '/team/kelly.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8],
      occupation: 'Customer Service Representative',
      aliases: [
        'The Business Bitch',
        'The Diet Bitch',
        'The Shopping Bitch',
        'The Etiquette Bitch',
      ],
      brand: 'Scranton',
      portrayed: 'Mindy Kaling',
      firstEp: 'Diversity Day',
      quotes: [
        "I don't talk trash, I talk smack. They're totally different. Trash talk is hypothetical, like: Your mom is so fat she can eat the internet. But smack talk is happening like right now. Like: You're ugly and I know it for a fact 'cause I got the evidence right there.",
        'I have a lot of questions. Number one, how dare you?',
      ],
      trivia:
        'Kelly has decided to call herself the business bitch, the diet bitch, the shopping bitch, and the etiquette bitch because it is important to brand yourself.',
    },
    {
      name: 'Ryan Howard',
      image: '/team/ryan.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8],
      occupation: 'Temp',
      aliases: [
        'Temp',
        'Fire Guy',
        'Kid',
        'Fired Guy',
        'Big Turkey',
        'Hired Guy',
        'Bryan',
        'Bobcat',
        'Douchebag',
        'Mr.Understood',
        'Rye-Guy',
        'Rye-Bread',
        'Shoe-bitch',
        'The Belle of the Ball',
        'Estaban the Cleaning Man',
        'Hottest in the office',
        'Little Old Man Boy',
        'The Guy Who Looks Like A Murderer',
      ],
      brand: 'Scranton',
      portrayed: 'B.J. Novak',
      firstEp: 'Pilot',
      quotes: [
        "Last year, Creed asked me how to set up a blog. Wanting to protect the world from being exposed to Creed's brain, I opened up a Word document on his computer and put an address at the top. I've read some of it. Even for the Internet, it's... pretty shocking.",
        'Stanley yelled at me today. That was one of the most frightening experiences of my life.',
      ],
      trivia:
        "B. J. Novak is one of the show's writing directors and executive producers. During this time, his role is significantly expanded to that of a main character.",
    },
    {
      name: 'Stanley Hudson',
      image: '/team/stanley.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Sales Representative',
      aliases: [
        'Stanley the Manly',
        'Stan',
        'Michael Scarn (narration)',
        'Florida Stanley',
        'Stankley',
        'Papa Bear (by Dwight)',
      ],
      brand: 'Scranton',
      portrayed: 'Leslie David Baker',
      firstEp: 'Pilot',
      quotes: [
        "I wake up every morning in a bed that's too small, drive my daughter to a school that's too expensive, and then I go to work to a job for which I get paid too little. But on pretzel day? Well, I like pretzel day.",
        'Did I stutter?',
      ],
      trivia:
        "Stanley begins to explain something in great detail to get people's attention, and it ends with, “...and shove it up your butt!”",
    },
    {
      name: 'Creed Bratton',
      image: '/team/creed.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Quality Assurance',
      aliases: [
        'Old Man',
        'Wacky Weed Tim',
        'William Charles Schneider',
        'Jeff Bomondo',
        'Papa Smurf',
        'Iron to the Fire',
      ],
      brand: 'Scranton',
      portrayed: 'Creed Bratton',
      firstEp: 'Pilot',
      quotes: [
        "Two eyes. Two ears. A chin. A mouth. Ten fingers. Two nipples. A butt, two kneecaps, a penis. I've just described to you the Loch Ness monster. And the reward for his capture? All the riches in Scotland. So I have one question: Why are you here?",
      ],
      trivia:
        'In a deleted scene from "The Convict", Creed states that he has been incarcerated before and that prison is where he obtained the name "Creed", though he later changes his story, implying that he had previously killed a man named Creed Bratton and assumed his identity.',
    },
    {
      name: 'Robert California',
      image: '/team/robert.jpg',
      seasons: [8],
      occupation: 'CEO',
      aliases: ['RC (by Darryl)', 'The F***ing Lizard King (by himself)', 'Bob Kazamakis'],
      brand: 'Sabre',
      portrayed: 'James Spader',
      firstEp: 'Search Committee',
      quotes: [],
      trivia:
        "Spader's acting had been particularly lauded by his fellow Office cast members. In an interview with Huffington Post, Brian Baumgartner stated that \"He has these demented arguments that on the surface make no sense, but he's talking, and suddenly and you're like, Oh yeah, that's right! That's right!\".",
    },
    {
      name: 'Nellie Bertram',
      image: '/team/nellie.jpg',
      seasons: [8, 9],
      occupation: 'Special Projects Manager',
      aliases: ['Nellie'],
      brand: 'Sabre',
      portrayed: 'Catherine Tate',
      firstEp: 'Search Committee',
      quotes: [],
      trivia:
        "The writers admit that they got Nellie off to a bad start as a conniving schemer, and they were unable to recover from that. They felt bad that they were wasting Catherine Tate's comedic talent.",
    },
    {
      name: 'Gabe Lewis',
      image: '/team/gabe.jpg',
      seasons: [6, 7, 8, 9],
      occupation: 'Coordinating Director for Emerging Regions',
      aliases: ['GSL', 'Birdman', 'Skeleton Man', 'Gabewad', 'Katy Perry'],
      brand: 'Sabre',
      portrayed: 'Zach Woods',
      firstEp: 'Moving On',
      quotes: ['Shut up about the sun. SHUT UP ABOUT THE SUN!'],
      trivia:
        'Gabe is the tallest character in the office coming at an inch taller than Jim. In the episode "Gettysburg" Zach Woods\' act on Abraham Lincoln is fully improvised.',
    },
    {
      name: 'Jo Benett',
      image: '/team/jo.jpg',
      seasons: [6, 7],
      occupation: 'CEO',
      aliases: ['Jolene'],
      brand: 'Sabre',
      portrayed: 'Kathy Bates',
      firstEp: 'Sabre',
      quotes: [],
      trivia:
        'She wrote an autobiography, titled Take a Good Look, and gave it to everyone in the office. She has multiple dogs; the seen ones named Calle, Jo Jr., Cornelius and BoBo.',
    },
    {
      name: 'Meredith Palmer',
      image: '/team/meredith.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Customer Service Representative',
      aliases: [
        'Mary-Beth (by Creed)',
        'Fire Girl',
        'Floozy',
        'Alkie',
        'Einstein (Sarcastically)',
        'Vomit Mop',
        'Floor Meat',
        'Flesh Hoover',
      ],
      brand: 'Scranton',
      portrayed: 'Kate Flannery',
      firstEp: 'Diversity Day',
      quotes: [],
      trivia:
        'Kate Flannery describes Meredith\'s fashion sense as "a messed up kindergarten teacher." The running joke of Meredith being caught topless bothered her father so much, he wrote her a letter that read, "Dear Kate, stop taking your clothes off. Love Dad.',
    },
    {
      name: 'Phyllis Vance',
      image: '/team/phyllis.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Sales Representative',
      aliases: [
        'Mama Goose',
        'Philly',
        'Easy Rider',
        'Phallus',
        'Bushiest Beaver',
        'Venus (by Luke Cooper)',
      ],
      brand: 'Scranton',
      portrayed: 'Phyllis Smith',
      firstEp: 'Pilot',
      quotes: [
        'I Wonder What People Like About Me? Probably My Jugs.',
        "I'm glad Michael's getting help. He has a lot of issues, and he's stupid.",
      ],
      trivia:
        'Phyllis invited Michael to her wedding because it was the only way she could get six weeks off for her honeymoon.',
    },
    {
      name: 'David Wallace',
      image: '/team/david.jpg',
      seasons: [2, 3, 4, 5, 6, 8, 9],
      occupation: 'CFO',
      aliases: ['Detective Wallace', 'David Walrus', "World's Best Boss"],
      brand: 'Dunder Mifflin',
      portrayed: 'Andy Buckley',
      firstEp: "Valentine's Day Alliance",
      quotes: [],
      trivia:
        'It is known he has a daughter which was referenced in "Secret Santa" who is in elementary school. Michael reveals he will pretend to be her to reach David in an emergency.',
    },
    {
      name: 'Karen Filippelli',
      image: '/team/karen.jpg',
      seasons: [3, 4],
      occupation: 'Sales Representative',
      aliases: ['The Other Woman'],
      brand: 'Stamford',
      portrayed: 'Rashida Jones',
      firstEp: 'Gay Witch Hunt',
      quotes: [],
      trivia:
        'Karen dates Jim Halpert throughout the third season. Outside of the Office universe, Rashida Jones and John Krasinski dated for a brief period of time.',
    },
    {
      name: 'Charles Miner',
      image: '/team/charles.jpg',
      seasons: [5],
      occupation: 'Vice President of Sales',
      aliases: ['Chuck'],
      brand: 'Dunder Mifflin',
      portrayed: 'Idris Elba',
      firstEp: 'New Boss',
      quotes: ['I am aware of the effect I have on Women'],
      trivia:
        'In "Secret Santa" all of corporate is fired, including Charles Miner and David Wallace by a company called Sabre. In "Viewing Party," when Michael is listing all his former bosses, he mentions Charles when he says "Charles was fired."',
    },
    {
      name: 'Cathy Simms',
      image: '/team/cathy.jpg',
      seasons: [8],
      occupation: 'Office Administrator',
      aliases: ['Cath', "Pam's Replacement"],
      brand: 'Scranton',
      portrayed: 'Lindsey Broad',
      firstEp: "Pam's Replacement",
      quotes: [],
      trivia:
        "According to John Krasinski, there were plans to write a scene depicting Jim making out with Cathy in Jim's hotel room. Krasinski objected to the plan, even refusing outright to shoot the scene as he believed this would potentially drive away the audience's goodwill in terms of the character if this were to occur.",
    },
    {
      name: 'Clark Green',
      image: '/team/clark.jpg',
      seasons: [9],
      occupation: 'Director of Sales',
      aliases: ['Chuck'],
      brand: 'Northeast Region',
      portrayed: 'Idris Elba',
      firstEp: 'New Boss',
      quotes: [],
      trivia:
        'Two deleted scenes in "Finale" hinted at a burgeoning relationship between Clark and Dakota, the accountant hired to replace Kevin.',
    },
    {
      name: 'Pete Miller',
      image: '/team/pete.jpg',
      seasons: [9],
      occupation: 'Customer Service Representative',
      aliases: ['Plop', 'New Jim'],
      brand: 'Scranton',
      portrayed: 'Jake Lacy',
      firstEp: 'New Guys',
      quotes: [],
      trivia:
        'Andy\'s habit of calling Pete "Plop" is reminiscent of him calling Jim "Big Tuna". In both cases, it\'s been debated whether or not Andy knows their real names.',
    },
    {
      name: 'Roy Anderson',
      image: '/team/roy.jpg',
      seasons: [1, 2, 3],
      occupation: 'Warehouse Worker',
      aliases: ["Dwight's punching bag"],
      brand: 'Scranton',
      portrayed: 'David Denman',
      firstEp: 'Pilot',
      quotes: [],
      trivia:
        'In "The Negotiation", Roy revealed that the only reason he tolerated Pam\'s friendship with Jim was because he thought that Jim was gay.',
    },
    {
      name: 'Todd Packer',
      image: '/team/todd.jpg',
      seasons: [2, 3, 6, 7, 8, 9],
      occupation: 'Traveling Salesman',
      aliases: ['Packer', 'Pack-Man', 'Packster', 'Wacky Pack'],
      brand: 'Scranton',
      portrayed: 'David Koechner',
      firstEp: 'Sexual Harassment',
      quotes: ['What has two thumbs and likes to bone your mom? This guy!'],
      trivia:
        "Fed up with Packer's presence in the office, Jim and Dwight prank Packer into leaving Dunder Mifflin and transferring to Sabre's corporate headquarters in Tallahassee, letting him quit to head out to the nonexistent job offer.",
    },
    {
      name: 'Toby Flenderson',
      image: '/team/toby.jpg',
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      occupation: 'Human Resources',
      aliases: [
        'Jerky Face',
        'Evil Snail',
        'The Antichrist',
        'Satan',
        'The Silent Killer',
        'Lemonhead',
        'Waste of Life',
        'The Worst',
        'Everything Wrong with the Paper Industry',
      ],
      brand: 'Scranton',
      portrayed: 'Paul Lieberstein',
      firstEp: 'Diversity Day',
      quotes: [
        "Chad Flenderman. Just an easy-going black guy who knows the streets--yet he also went to Oxford. So. Just as comfortable on a motorcycle as he is on Air Force One. Oh and he's also the world's leading Egyptologist.",
      ],
      trivia:
        'When Michael gives his two weeks notice, Toby shows he is not as resentful towards Michael as Michael is to him in a talking head, referring to him as "a movie on an airplane, which is nothing special but something to watch".',
    },
    {
      name: 'AJ',
      aliases: ['Fatty'],
      occupation: 'Sales Representative',
      brand: 'Nashua',
      seasons: [5, 7],
      portrayed: 'Rob Huebel',
      image: '/team/aj.jpg',
      firstEp: 'Lecture Circuit Part 2',
      quotes: [],
      trivia:
        'Actor Rob Huebel would be stopped on the street by fans of the show who tell him, "You have to get out of the way, man."',
    },
  ]

  if (name === 'all') {
    return characters
  }

  return characters.find((item) => item.name.replace(/\s+/g, '') === name)
}
